### ISSUE TITLE
Proper image tags missing

### ISSUE THREAD

**Issue by bruecktech** [rebuy-de/node-drainer#80]
Hello,

we at Personio are users of your tool.
Unfortunately your latest [commit to master](https://github.com/rebuy-de/node-drainer/commit/176ec5048ac8f5208493a83238d4438eb568c16b) broke the tool for us as there is no versioning available in the quay repository and we had to use `quay.io/rebuy/node-drainer:master`
Could you please introduce version tagging for your images (e.g. based on the commit sha) so that we can pin the version?

Thanks and also thanks for providing the tool!
Johannes

**Comment by svenwltr** [comment]
Hello. Same answer as in https://github.com/rebuy-de/node-drainer/issues/81. We did not expect anyone using it. We will clean up the tags and introduce a proper versioning.

Sorry for the inconvenience.

**Comment by svenwltr** [comment]
Hello. It took a bit longer, but we now tagged the latest stable version: https://github.com/rebuy-de/node-drainer/releases/tag/v2.1.0
